### ISSUE TITLE
[bug] [firefox] icons do not scale properly

### ISSUE THREAD

**Issue by andreivictor** [dimaslz/ng-heroicons#1]
hello,

first of all, thanks for this project.

I've found a bug in Firefox - the icons do not scale properly. 
Please check the attached screenshot: https://i.imgur.com/vk1uF4C.png

**Comment by dimaslz** [comment]
Hello @andreivictor, thanks for the notice, I have cathed the error, I will update soon.

Welcome, I appreciate your support :)

**Comment by dimaslz** [comment]
Hello @andreivictor, the issue is solved, you can test it here: https://qvbvh.csb.app/. version 0.0.3

Thank you, kind regards!

**Comment by andreivictor** [comment]
Awesome! Thanks a lot!
