### ISSUE TITLE
Setting default values through .forRoot()

### ISSUE THREAD

**Issue by gwesterman** [dimaslz/ng-heroicons#293]
It would be useful, if one could set default values through .forRoot().

In my case I prefer a stroke width of 2 on all my icons and would rather not have to set it every time I include an icon in my template.

**Comment by dimaslz** [comment]
Hello @gwesterman, thank you for your comment, I will take a look soon. 

Thanks ✋

**Comment by dimaslz** [comment]
Hello @gwesterman 

Late but finally here. From the [version 1.18.1](https://www.npmjs.com/package/@dimaslz/ng-heroicons/v/1.18.1) finally is possible setup the default config by the ".forRoot()".

Thank you!
