### ISSUE TITLE
Angular 15 upgrade

### ISSUE THREAD

**Issue by mbernatovic** [dimaslz/ng-heroicons#362]
can you upgrade project to be compatible with angular 15 ?

**Comment by dimaslz** [comment]
Thank you for your interest, I will work on some updates this week and try to include this request https://github.com/dimaslz/ng-heroicons/issues/293 as well.

**Comment by mbernatovic** [comment]
Hey, thanks for updating. I noticed that you pushed code to github but it's not reflected to npm. i don't see new version of it on npm.

also one thing. i can see that whole project size is 7.44 MB can you make that is tree shakable so that build does not include files if im not using it ?

Thanks

**Comment by mbernatovic** [comment]
@dimaslz any update on this ?

**Comment by dimaslz** [comment]
i created an specific version for Angular v15. https://www.npmjs.com/package/@dimaslz/ng-heroicons
