### ISSUE TITLE
Angular 17 Support

### ISSUE THREAD

**Issue by dagistan-tuncbilek** [dimaslz/ng-heroicons#395]
Angular 17 Support please.

**Comment by dimaslz** [comment]
Hello @dagistan-tuncbilek , I tested after the release but, you are right, need an update. I will work on it this weekend.

Thank you for notice.

**Comment by dimaslz** [comment]
Hello @dagistan-tuncbilek , I was testing in a clean Angular v17 version with NgHeroicons 1.6.0 and looks like is working properly.

https://stackblitz.com/edit/stackblitz-starters-kyagyc

Do you have an special issue?, please share screenshot or share a stackblitz or codesandbox to check in detail.

In mean while, I working in a new version to update the NPM home and v17 playground.

**Comment by dagistan-tuncbilek** [comment]
Thank you. It seems okay for me. I am trying your library almost for a month and it is really perfect match for some of my applications and i am planning to use it. This is really a very useful library. Thanks for quick angular 17 support.

**Comment by dagistan-tuncbilek** [comment]
Hi again, i don't want to bother you, but are you planning to deploy compatible version for Angular 17? I don't like to install by --force.

**Comment by jamieb25** [comment]
@dimaslz - I am having the same issue as @dagistan-tuncbilek. It is supported but I am unable to `npm install` without using `--force` due to the peer dependencies of angular being ^16

**Comment by dimaslz** [comment]
Hello @jamieb25 and @dagistan-tuncbilek 

Sorry for the delay. To be honest, I skipped the idea to work in the version 17 because I understood that the v16 was enough. 

Then, if you are experimenting issues, let me plan this weekend to deploy the last version.

BTW, you never bother me, in fact I am happy to work in a useful opensource.

Thank to notice and sorry again for the delay.

**Comment by dimaslz** [comment]
Hello @jamieb25 and @dagistan-tuncbilek 

Version 1.7.0 with support for Angular 17 just been released: https://www.npmjs.com/package/@dimaslz/ng-heroicons

Let me know that all is good.

Thanks

**Comment by dagistan-tuncbilek** [comment]
@dimaslz Thanks a lot.
